name: Run Playwright with Chrome Profile

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Playwright browser path
        run: echo "PLAYWRIGHT_BROWSERS_PATH=0" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Force install Chromium browser
        run: |
          npx playwright install chromium

      - name: Verify browser installation
        run: |
          ls -l /home/runner/.cache/ms-playwright/chromium* || echo "Chromium not found"

      - name: Run scraper
        run: python core/main.py
