name: Playwright Scraper

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/10 * * * *'  # Adjust cron as needed

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable xvfb p7zip-full
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium

      - name: Verify Profile3.7z exists
        run: |
          ls -l Profile3.7z
          file Profile3.7z

      - name: Extract Chrome Profile
        run: |
          if [[ -f "Profile3.7z" ]]; then
            7z x Profile3.7z -o./chrome-profile
          else
            echo "Profile3.7z not found!"
            exit 1
          fi

      - name: Run Playwright scraper
        run: |
          xvfb-run -a python core/main.py
        env:
          LINKEDIN_USERNAME: ${{ secrets.LINKEDIN_USERNAME }}
          LINKEDIN_PASSWORD: ${{ secrets.LINKEDIN_PASSWORD }}
