name: Run Playwright with Chrome Profile

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Chrome Profile
        run: |
          wget --no-check-certificate 'https://drive.google.com/uc?export=download&id=1J9Zjq2RYq6ojuCL6KwwGKUKMePABOowJ' -O chrome-profile.zip
          unzip chrome-profile.zip -d ./chrome-profile

      - name: Run scraper
        run: |
          python core/main.py
        env:
          PLAYWRIGHT_BROWSERS_PATH: 0
